# A Quick Primer on Python Matrices using Numpy


This notebook uses **Numerical Python** (NumPy) to create various array types and to compute some mathematical operations with these arrays.

## Get Modules for this Notebook

In [1]:
import numpy as np

## Multidimensional Arrays

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only a few lines of code. This can be a huge advantage when performing math operations on large datasets.

The array object in NumPy is called **ndarray** meaning 'n-dimensional array'. In NumPy, all of the elements within the array are of the same type.

What is a NumPy array, and how is it different from a list? 

Ans:

A NumPy array is an n-dimensional grid of homogenous-type values indexed by a tuple of nonnegative integers. The primary difference compared with a Python list is that a NumPy array cannot change the size by which it was created once defined. 
Moreover, the data types are coherent. Since lists can only hold a few types of data and extend their lengths, while NumPy arrays have much richer support for complex math operations and optimize performance, they are intended to be used instead of lists, especially if numerical operations need to be done.

* **one-dimensional array ('1-D')**
    - The most common of array types. A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type.



<p>
  <img alt="Numpy Array Visualizations" src="images/numpy_array_types.png" width="400" height="200"/>
</p>

[img source](https://github.com/greyhatguy007/Mathematics-for-Machine-Learning-and-Data-Science-Specialization-Coursera/blob/main/C1/w1/lab/images/visualization.png)

In [2]:
# One dimensional array - one row several columns
one_d_array = np.array([1, 2, 3])
print(one_d_array)

[1 2 3]


In [3]:
# Two dimensional array
two_d_array = np.array([[5.2, 3.0, 4.5],
                        [9.1, 0.1, 0.3]])
print(two_d_array)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


In [4]:
two_d_array.shape # the shape (rows, columns) of the array
two_d_array.ndim # number of dimensions of the array
two_d_array.size # stores the number of elements in the array

6

#### Creating the 3-D NumPy array shown in the picture shape (4,3,2)

To create the 3D array shown in the image, you'll need to use NumPy. The array has a shape of (4, 3, 2), which means it has 4 layers (along axis 0), each with 3 rows (along axis 1) and 2 columns (along axis 2).

The following Python code uses the `numpy.array()` function to create this 3D array. Each inner list represents a 2D slice of the 3D array.

##### Understanding a 2D Slice
A 2D slice of a 3D array is simply one of the two-dimensional planes that make up the larger, three-dimensional structure. Think of a 3D array as a stack of pages. Each page in that stack is a 2D array (a grid of rows and columns). When you take a "slice" of the 3D array, you're essentially pulling out one of those individual pages.

In the example image, the 3D array has a shape of 

(axis=0, axis=1, axis=2) = (Dimension/layer, Height/row, Width/columns) = (4, 3, 2).

* Axis=0, depth = 4 slices, layers

* Axis=1, height = 3 rows

* Axis=2, width = 2 columns


We can think of the array in the picture as 

* A stack of four 2D arrays, where each 2D array has a shape of (3, 2) (3 rows and 2 columns).


#### How to interpret this 3-D example

4x3x2 = 24 possible values but we can't see all of the values in col2, so notice that I have made those dummy values (e.g., 888) for emphasis.

| Dimension=4  | Height/Row=3 | Width/ColumnCity=2| = |value at that position in the drawing|
|--|--|--| -- | ---|
|Depth 0| | | ||
|0 | 0 | 0| = |  1|
|0 | 0 | 1| = |  2|
|0 | 1 | 0| = |  4|
|0 | 1 | 1| = |  3|
|0 | 2 | 0| = |  7|
|0 | 2 | 1| = |  4|
|Depth 1| | | ||
|1 | 0 | 0| = |  2|
|1 | 0 | 1| = |  888 - dummy value not seen in the figure|
|1 | 1 | 0| = |  9|
|1 | 1 | 1| = |  888 - dummy value not seen in the figure|
|1 | 2 | 0| = |  7|
|1 | 2 | 1| = |  5|
|Depth 2| | | ||
|2 | 0 | 0| = |  1|
|2 | 0 | 1| = |  888 - dummy value not seen in the figure|
|2 | 1 | 0| = |  3|
|2 | 1 | 1| = |  888 - dummy value not seen in the figure|
|2 | 2 | 0| = |  0|
|2 | 2 | 1| = |  2|
|Depth 3| | | ||
|3 | 0 | 0| = |  9|
|3 | 0 | 1| = |  888 - dummy value not seen in the figure|
|3 | 1 | 0| = |  6|
|3 | 1 | 1| = |  888 - dummy value not seen in the figure|
|3 | 2 | 0| = |  9|
|3 | 2 | 1| = |  8|

#### So translating the above into Numpy 2D arrays to form the final 3 D array


In [5]:
# Create the 3D array
array_3d = np.array([
    [[1, 2], [4, 3], [7, 4]],
    [[2, 888], [9, 888], [7, 5]],
    [[1, 888], [3, 888], [0, 2]],
    [[9, 888], [6, 888], [9, 8]]
])

# Print the array to verify its contents
print(array_3d)

# Print the shape to confirm it's (4, 3, 2)
print(array_3d.shape)

[[[  1   2]
  [  4   3]
  [  7   4]]

 [[  2 888]
  [  9 888]
  [  7   5]]

 [[  1 888]
  [  3 888]
  [  0   2]]

 [[  9 888]
  [  6 888]
  [  9   8]]]
(4, 3, 2)


---

## Array Math Operations

NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. 

The operations are performed using the math symbol for each '+', '-' and '*'. Recall that addition of Python lists works completely differently as it would append the `lists`, thus making a longer list, in addition, subtraction and multiplication of Python lists do not work.



In [6]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

In [7]:
# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)



[ 3  7 11]
[1 1 1]
[ 2 12 30]


## Broadcasting - Multiplying Vector with a Scalar

Broadcasting allows you to perform operations specifically on arrays of different shapes.

In [8]:
vector_original = np.array([1, 2])
vector_broadcasting = vector_original * 2.0

print(f"Original Vector = {vector_original}")
print(f"Vector post broadcasting = {vector_broadcasting}")

Original Vector = [1 2]
Vector post broadcasting = [2. 4.]


---

### Matrxi Equation Terminology

#### Matrix Algebra is Useful for Linear Transformation s

Transform **X** and **Y** coordinates through multiplication and addition. Here, **X** and **Y** are matrices/vectors

##### Example transforming original **X** and **Y** 

$ x_\bold{\text{new}} = (\bold{x} \times -1) + (\bold{y} \times 0) $

$ y_\bold{\text{new}} = (\bold{x} \times 0) + (\bold{y} \times -1) $


<p>
  <img alt="Linear Transformation" src="images/linear_transform.png" width="300" height="200"/>
</p>


<p>
  <img alt="Vector Multiplicaton Row x Column" src="images/vector_multiplication.png" width="350" height="200"/>
</p>



<br>

##### Transpose 

Changing the rows in a matrix into corresponding columns is **Transposing** a matrix

<p>
  <img alt="Transpose" src="images/transpose_function.png" width="350" height="200"/>
</p>

In [9]:
# Matrix Algebra
a = [2,1]
W = np.array([[0,1], [-1,0]])
b = np.dot (a,W)
print(a)
print(W)
print(b)

[2, 1]
[[ 0  1]
 [-1  0]]
[-1  2]


In [10]:
# Transpose
a_transpose = np.transpose(a)
print(a_transpose)

W_transpose = np.transpose(W)
print(W_transpose)

b_transpose = np.transpose(b)
print(b_transpose)


b_transpose == np.dot(W_transpose, a_transpose)

[2 1]
[[ 0 -1]
 [ 1  0]]
[-1  2]


array([ True,  True])